version: '3.8'

volumes:
  db_volume:

networks:
  db_network:
  site_network:

services:
  mysql:
    build: ./mysql
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "5655:3306" 
    expose:
      - "3306" 
    volumes:
      - "db_volume:/var/lib/mysql"
      - "${PWD}/mysql/conf/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword" 
      MYSQL_USER: "myuser" 
      MYSQL_PASSWORD: "mypassword" 
      MYSQL_DATABASE: "test_db" 
    networks:
      db_network:
        aliases:
          - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: ./app
    image: app
    container_name: app_container
    ports:
      - "4743:4743" 
    expose:
      - "4743" 
    networks:
      db_network:
      site_network:
        aliases:
          - app
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "5423:824"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      site_network:
    depends_on:
      app:
        condition: service_healthy