version: '3.8'

volumes:
  db_volume:


networks:
  db_network:
  site_network:


services:
  mysql:
    build: ./mysql
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "5655:3306" # Redirection du port 3306 de MySQL vers le port 5655 sur la machine hôte
    expose:
      - "3306" # Expose le port interne pour la communication avec d'autres services dans le même réseau
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/conf/init.sql:/docker-entrypoint-initdb.d/init.sql # Chargement du script d'initialisation
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword" # Mot de passe root pour MySQL
      MYSQL_USER: "myuser" # Utilisateur de la base de données
      MYSQL_PASSWORD: "mypassword" # Mot de passe de l'utilisateur
      MYSQL_DATABASE: "test_db" # Base de données à créer
    networks:
      db_network:
        aliases:
          - mysql

  app:
    build: ./app
    image: app
    container_name: app_container
    ports:
      - "4743:4743" # Redirige le port 4743 de l'application Flask
    expose:
      - "4743" # Expose le port interne de l'application pour les communications internes
    networks:
      db_network:
      site_network:
        aliases:
          - app

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "5423:824" # Redirige le port 824 du conteneur vers le port 5423 de la machine hôte
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx config
    networks:
      site_network:
